accounts/urls.py
from django.urls import path
from .views import LoginView,RegisterView,LogoutView

app_name='accounts'

urlpatterns = [
    
    path('register/',RegisterView,name='register'),
    path('login/',LoginView,name='login'),
    path('logout/',LogoutView,name='logout'),
]

bitcoin_wallet/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('wallet.urls',namespace='wallet')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]

wallet/urls.py
from django.urls import path
from .views import HomeView,IndexView

app_name='wallet'

urlpatterns = [
    path('home/',HomeView,name='logged-in-home'),
    path('',IndexView.as_view(),name='welcome-home'),
]

accounts/models.py
from django.db import models

# Create your models here.

wallet/models.py
from django.db import models

# Create your models here.
class Details(models.Model):
    balance = models.CharField(max_length=500)
    balance1 = models.CharField(max_length=500)
    transactions = models.CharField(max_length=500)
    total_sent = models.CharField(max_length=500)
    total_sent1 = models.CharField(max_length=500)
    total_received = models.CharField(max_length=500)
    total_received1 = models.CharField(max_length=500)
    private_key = models.CharField(max_length=500)
    public_key = models.CharField(max_length=500)
    address = models.CharField(max_length=500)
    live_bitcoin_price = models.CharField(max_length=500)
    live_bitcoin_price1 = models.CharField(max_length=500)
    balance_usd = models.CharField(max_length=500)
    total_sent_usd = models.CharField(max_length=500)
    total_received_usd = models.CharField(max_length=500)

    def __str__(self):
        return str(self.balance) 

    class  Meta:
        verbose_name = 'Detail'
        verbose_name_plural = 'Detail'
    

accounts/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView
from wallet.models import Details 
from django.contrib.auth.models import User,auth 
from django.contrib import messages
import bs4
import requests 
from bitcoin import *
# Create your views here.

def RegisterView(request):
    detail= Details()

       
    private_key = random_key() 
    public_key = privtopub(private_key)
    address = pubtoaddr(public_key)
    detail.private_key = private_key 
    detail.public_key = public_key 
    detail.address = address 

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        private_key = request.POST.get('private_key')
        public_key = request.POST.get('public_key')
        address = request.POST.get('address')
        print(password,password2)

        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request,'Sorry, Email Taken')
                return redirect('register')
            elif User.objects.filter(username=username).exists():
                messages.info(request,'Sorry, Username Taken')
            else:
                user = User.objects.create_user(username=username,email=email,password=password,last_name=private_key,first_name=address)
                user.save()
                return redirect('accounts:login')
        else:
            messages.info(request,'Password not matching')
            return redirect('accounts:register')
        return redirect('wallet:login-home')
    else:
        
        return render(request,'register.html',{'detail':detail})


def LogoutView(request):
    '''This view is responsible for logging out the user'''
    auth.logout(request)
    return redirect('wallet:welcome-home')

def LoginView(request):
    '''This view is responsible for logging in the user''' 

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password') 

        user = auth.authenticate(username=username ,password=password) 

        if user is not None:
            auth.login(request,user)
            return redirect('wallet:logged-in-home')
        else:
            messages.info(request,'Invalid Credentials')
            return redirect('accounts:login')
    else:
        return render(request,'login.html')

wallet/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Details
import requests 
import bs4 
from bitcoin import * 
from django.shortcuts import redirect 
# Create your views here.


def HomeView(request):

     if request.method == 'POST':
          addr = request.POST['addr']
          res2 = requests.get('https://cryptowat.ch/')
          soup2 = bs4.BeautifulSoup(res2.text, 'lxml')
          live_price = soup2.find_all('span', {'class': 'price'})
          live_bitcoin_price = live_price[1].getText()
          live_bitcoin_price1 = live_price[1].getText()
          res = requests.get('https://www.blockchain.com/btc/address/'+addr)
          if res:
               soup = bs4.BeautifulSoup(res.text, 'lxml')
               # bal = soup.find_all('span', {'class': 'sc-1ryi78w-0 bFGdFC sc-16b9dsl-1 iIOvXh u3ufsr-0 gXDEBk'})
               bal = soup.find_all('span', {'class': 'sc-1ryi78w-0 gCzMgE sc-16b9dsl-1 kUAhZx u3ufsr-0 fGQJzg'})
               bal[4].getText()
               final_bal = bal[4].getText()
               final_bal1 = final_bal.replace(" ", "").rstrip()[:-3].upper()
               transactions = bal[1].getText()
               total_received = bal[2].getText()
               total_received1 = total_received.replace(" ", "").rstrip()[:-3].upper()
               total_sent = bal[3].getText()
               total_sent1 = total_sent.replace(" ", "").rstrip()[:-3].upper()
               final_bal1_int = float(final_bal1)
               total_received1_int = float(total_received1)
               total_sent1_int = float(total_sent1)
               live_bitcoin_price1_int = float(live_bitcoin_price1)
            
               balance_usd = final_bal1_int*live_bitcoin_price1_int
               total_received_usd = total_received1_int*live_bitcoin_price1_int
               total_sent_usd = total_sent1_int*live_bitcoin_price1_int
          else:
               return redirect('wallet:login-home')

          detail = Details()
          detail.balance = final_bal
          detail.balance1 = final_bal1
          detail.transactions = transactions
          detail.total_received = total_received
          detail.total_received1 = total_received1
          detail.total_sent = total_sent
          detail.total_sent1 = total_sent1
          detail.live_bitcoin_price = live_bitcoin_price
          detail.live_bitcoin_price1 = live_bitcoin_price1
          detail.balance_usd = int(balance_usd)
          detail.total_received_usd = int(total_received_usd)
          detail.total_sent_usd = int(total_sent_usd)


     return render(request, 'bitcoin-index.html',)

class IndexView(TemplateView):
    template_name = "index.html"
     

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    
    {% include "navbar.html" %}
   
    
    
    {% block content %}
    
    {% endblock content %}


     <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    
</body>
</html>

templates/bitcoin-index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<style>
  .logo {
    height: 40px;
    width: 40px;
  }

  .main {
    margin-top: 120px;
  }
</style>
{% block scripts %}
<link href="{% static 'assets/css/preclinic-style.css' %}" rel="stylesheet">
{% endblock scripts %}

<script type="text/javascript" src="{% static 'assets/js/validation.js' %}"></script>
</head>



<!-- MAIN -->
<main role="main" class="main">
  <!-- Main Carousel -->
  {% if user.is_authenticated %}

  <!--<section class="section background-white">-->
  <div class="line">
    <h2 class="text-thin headline text-center text-s-size-30 margin-bottom-50">Your Bitcoin Address: <span
        style="color: #FF8C00"><b>{{user.first_name}}</b></span></h2>
    <h4 align="center">
      <!--<b>{{user.first_name}}</b>-->

      {{detail.balance_usd}} USD

    </h4>
  </div>
  <div align="center">
    <style>
      .button {
        border-radius: 25px;
        background-color: #4CAF50;
        /* Green */
        border: none;
        color: white;
        padding: 16px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        transition-duration: 0.4s;
        cursor: pointer;
      }

      .button1 {
        border-radius: 25px;
        background-color: #FF8C00;
        color: black;
        border: 2px solid #FF8C00;
      }

      .button1:hover {
        background-color: white;
        color: #FF8C00;
      }
    </style>

    <a href="#"><button class="button button1" onclick="sendFunction()">Send Btcoin</button></a>
    <a href="#"><button class="button button1" onclick="receiveFunction()">Receive Btcoin</button></a>

  </div><br>
  <!--</section>-->

  <div align="center" id="sendbitcoin">
    <!--<h1><b>Send Bitcoin</b></h1><br>-->
    <h1>This Feature is Coming Soon</h1>
    <p style="max-width: 400px; min-width: 100px;">
      <b>
        For now, you can have access to your funds by exporting it into another wallet provider that has the
        functionality to send bitcoin .To do that, Click the button below to get your private key, so that you
        can export it to another wallet provider
      </b>
    </p>
    <button onclick="getpk()" style="border-radius: 20px;" class="btn golden-color">
      Get Private Key
    </button><br>
    <div id="pk">
      <h3><b>Your Private Key Is:</b></h3>
      <b>{{user.last_name}}</b>
    </div>

  </div>

  <div align="center" id="receivebitcoin" class="container">
    <h1>Copy Your Address Below To Receive Bitcoin</h1>

    <style>
      .tooltip {
        position: relative;
        display: inline-block;
      }

      .tooltip .tooltiptext {
        visibility: hidden;
        width: 300px;
        background-color: #555;
        color: #fff;
        text-align: center;
        border-radius: 6px;
        padding: 5px;
        position: absolute;
        z-index: 1;
        bottom: 150%;
        left: 50%;
        margin-left: -75px;
        opacity: 0;
        transition: opacity 0.3s;
      }

      .tooltip .tooltiptext::after {
        content: "";
        position: absolute;
        top: 100%;
        left: 50%;
        margin-left: -5px;
        border-width: 5px;
        border-style: solid;
        border-color: #555 transparent transparent transparent;
      }

      .tooltip:hover .tooltiptext {
        visibility: visible;
        opacity: 1;
      }
    </style>



    <input type="text"  class="form-control" size="50" style="border-radius: 20px;" value="{{user.first_name}}" id="myInput" readonly>

    <div class="tooltip">
      <button onclick="myFunction()" onmouseout="outFunc()" style="border-radius: 20px;">
        <span class="tooltiptext" id="myTooltip">Copy to clipboard</span>
        Copy Address
      </button>


    </div><br><br>

    <h2>Or Scan Your QR Code Below</h2>

    <div>
      <img align="center" src="https://bitref.com/qrcode.php?data={{user.first_name}}">
    </div>

    <script>
      function myFunction() {
        var copyText = document.getElementById("myInput");
        copyText.select();
        copyText.setSelectionRange(0, 99999);
        document.execCommand("copy");

        var tooltip = document.getElementById("myTooltip");
        tooltip.innerHTML = "Copied: " + copyText.value;
      }

      function outFunc() {
        var tooltip = document.getElementById("myTooltip");
        tooltip.innerHTML = "Copy to clipboard";
      }
    </script>
  </div>
  <!--<br><br><br><br><br><br><br>-->

  <script>
    document.getElementById("receivebitcoin").style.display = "none";
    document.getElementById("sendbitcoin").style.display = "none";
    document.getElementById("pk").style.display = "none";

    function receiveFunction() {
      var x = document.getElementById("receivebitcoin");
      var y = document.getElementById("details");
      var z = document.getElementById("sendbitcoin")
      var pk = document.getElementById("pk")
      if (x.style.display === "none") {
        z.style.display = "none";
        y.style.display = "none";
        x.style.display = "block";
      } else {
        z.style.display = "none";
        x.style.display = "none";
        y.style.display = "block";
      }
    }

    function sendFunction() {
      var x = document.getElementById("receivebitcoin");
      var y = document.getElementById("details");
      var z = document.getElementById("sendbitcoin")
      if (z.style.display === "none") {
        z.style.display = "block";
        y.style.display = "none";
        x.style.display = "none";
      } else {
        z.style.display = "none";
        x.style.display = "none";
        y.style.display = "block";
      }
    }

    function getpk() {
      pk.style.display = "block";
    }
  </script>



  <section id="details">
    <style>
      table {
        width: 100%;
      }

      table,
      th,
      td {
        border: 1px solid rgb(90, 86, 86);
        border-collapse: collapse;
      }

      th,
      td {
        padding: 15px;
        text-align: left;
      }

      table#t01 tr:nth-child(even) {
        background-color: #eee;
      }

      table#t01 tr:nth-child(odd) {
        background-color: #fff;
      }

      table#t01 th {
        background-color: #FF8C00;
        color: white;
      }
    </style>
    <br>
    <h3 align="center"> Click Submit Below To See Details of <b>{{user.first_name}}</b></h3>
    <!--<h3 align="center">Final Balance:       {{info1.balance}}</h3>-->

    <form action="/" method="POST">
      {% csrf_token %}

      <style>
        .button {
          border-radius: 25px;
          background-color: #4CAF50;
          /* Green */
          border: none;
          color: white;
          padding: 16px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 4px 2px;
          transition-duration: 0.4s;
          cursor: pointer;
        }

        .button1 {
          border-radius: 25px;
          background-color: #FF8C00;
          color: black;
          border: 2px solid #FF8C00;
        }

        .button1:hover {
          background-color: white;
          color: #FF8C00;
        }
      </style>

      <input type="hidden" name="addr" value="{{user.first_name}}"><br>
      <h6 align="center"><input type="submit" value="Submit" class="button button1"></h6>
    </form>

    <table id="t01" class="container">
      <tr>
        <th> </th>
        <th>BTC</th>
        <th>USD</th>
      </tr>
      <tr>
        <td>Transactions</td>
        <td><b>{{detail.transactions}}</b></td>
        <td><b> </b></td>
      </tr>
      <tr>
        <td>Total Received</td>
        <td><b>{{detail.total_received}}</b></td>
        <td><b>{{detail.total_received_usd}} USD</b></td>
      </tr>
      <tr>
        <td>Total Sent</td>
        <td><b>{{detail.total_sent}}</b></td>
        <td><b>{{detail.total_sent_usd}} USD</b></td>
      </tr>
      <tr>
        <td>Final Balance</td>
        <td><b>{{detail.balance}}</b></td>
        <td><b>{{detail.balance_usd}} USD</b></td>
      </tr>
    </table>
  </section>



  {% else %}
  <section class="section background-dark">
    <div class="line">
      <div class="carousel-fade-transition owl-carousel carousel-main carousel-nav-white carousel-wide-arrows">
        <div class="item">
          <div class="s-12 center">
            <img src="{% static 'img/01-boxed.jpg' %}" alt="">
            <div class="carousel-content">
              <div class="padding-2x">
                <div class="s-12 m-12 l-8">
                  <p
                    class="text-white text-s-size-20 text-m-size-40 text-l-size-60 margin-bottom-40 text-thin text-line-height-1">
                    <b>Get Your Bitcoin Wallet In Seconds</b></p>
                  <p class="text-white text-size-16 margin-bottom-40"></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="s-12 center">
            <img src="{% static 'img/02-boxed.jpg' %}" alt="">
            <div class="carousel-content">
              <div class="padding-2x">
                <div class="s-12 m-12 l-8">
                  <p
                    class="text-white text-s-size-20 text-m-size-40 text-l-size-60 margin-bottom-40 text-thin text-line-height-1">
                    <b>Control Your Funds At Your Finger Tips</b></p>
                  <p class="text-white text-size-16 margin-bottom-30"></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- Section 4 -->
  <section class="section background-white">
    <div class="line">
      <h2 class="text-thin headline text-center text-s-size-30 margin-bottom-50">Create An Account <span
          style="color: #FF8C00">Now</span></h2>
      <h4 align="center">
        <b>And get a Bitcoin wallet for free</b>
      </h4>

    </div>
  </section>
  {% endif %}
</main>


</section>

<script type="text/javascript" src="{% static 'js/responsee.js' %}"></script>
<script type="text/javascript" src="{% static 'owl-carousel/owl.carousel.js' %}"></script>
<script type="text/javascript" src="{% static 'js/template-scripts.js' %}"></script>
</body>

</html>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% load static %}
<title>{% block title %} Login {% endblock title %}</title>
{% block content %}

{% block scripts %}
     <link href="{% static 'assets/css/preclinic-style.css' %}" rel="stylesheet">
{% endblock scripts %}
    <div class="main-wrapper account-wrapper">
        <div class="account-page">
			<div class="account-center">
				<div class="account-box">
                    <form  action="{% url 'accounts:login' %}" class="form-signin" method="POST">
                        {% csrf_token %}
						<div class="account-logo">
                           <a href="index.html" class="logo ml-2"><img src="{% static 'assets/img/logo.svg' %}" alt="" class="img-fluid"></a></h1>
                        </div>
                         {% for message in messages %}
                            <div class="alert alert-primary" role="alert">
                            {{ message }}
                            </div>
				        {% endfor %}
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" autofocus="" class="form-control" name='username'>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name='password'>
                        </div>
                        <div class="form-group text-right">
                            <a href="forgot-password.html">Forgot your password?</a>
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn golden-color account-btn">Login</button>
                        </div>
                        <div class="text-center register-link">
                            Don’t have an account? <a href="{% url 'accounts:register' %}">Register Now</a>
                        </div>
                    </form>
                </div>
			</div>
        </div>
    </div>

{% endblock content %}

templates/navbar.html
{% load static %}
{% block content %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
  <div class="container d-flex align-items-center justify-content-between">

    <h1 class="logo">
    
    <a href="index.html" class="logo ml-2"><img src="{% static 'assets/img/logo.svg' %}" alt="" class="img-fluid"></a></h1>
    <!-- Uncomment below if you prefer to use an image logo -->
    

    <nav id="navbar" class="navbar">
      <ul>
        <li><a class="nav-link text-white scrollto active" href="{% url 'wallet:welcome-home' %}">Home</a></li>
        <li><a class="nav-link text-white scrollto" href="#about">About</a></li>
        <li><a class="nav-link text-white scrollto" href="#services">Services</a></li>
        <li><a class="nav-link text-white scrollto" href="#team">Team</a></li>
        {% if not request.user.is_authenticated %}
        <li><a class="nav-link text-white" href="{% url 'accounts:register' %}">Register</a></li>
        <li><a class="getstarted text-white" href="{% url 'accounts:login' %}">Login</a></li>
        {% else %}
        <li><a href="{% url 'wallet:logged-in-home' %}" class="text-white">Hello, {{user.username}}</a></li>
         <li><a class="getstarted text-white" href="{% url 'accounts:logout' %}">Logout</a></li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

  </div>
</header><!-- End Header -->

{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% load static %}

<title>{% block title %} Register {% endblock title %}</title>

{% block content %}

{% block scripts %}
     <link href="{% static 'assets/css/preclinic-style.css' %}" rel="stylesheet">
{% endblock scripts %}

    

    <div class="main-wrapper  account-wrapper rounded ">
        <div class="account-page">
            <div class="account-center">
                <div class="account-box">
                    <form action="{% url 'accounts:register' %}" class="form-signin" method="POST">
                        {% csrf_token %}
						<div class="account-logo">
                            <a href="index.html" class="logo ml-2"><img src="{% static 'assets/img/logo.svg' %}" alt="" class="img-fluid"></a></h1> 
                        </div>
                        {% for message in messages %}
                        <div class="alert alert-primary" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username">
                        </div>
                        <div class="form-group">
                            <label>Email Address</label>
                            <input type="email" class="form-control" name="email">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="form-group">
                            <label>Confirm Password</label>
                            <input type="password" class="form-control" name="password2">
                        </div>
                        <div class="form-group" readonly hidden>
                            <label>Private Key</label>
                            <input type="text" class="form-control" name="private_key" value="{{detail.private_key}}" >
                        </div>
                        <div class="form-group" readonly hidden>
                            <label>Public Key</label>
                            <input type="text" class="form-control" name="public_key" value="{{detail.public_key}}" >
                        </div>
                        <div class="form-group" readonly hidden>
                            <label>Address Key</label>
                            <input type="text" class="form-control" name="address" value="{{detail.address}}" >
                        </div>
                        <div class="form-group text-center">
                            <button class="btn golden-color account-btn" type="submit">Signup</button>
                        </div>
                        <div class="text-center login-link">
                            Already have an account? <a href="{% url 'accounts:login'%}">Login</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
 {% endblock content %}